name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies (rosdep)
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-select ROS2_wear

      - name: Run test.bash
        run: |
          source /opt/ros/humble/setup.bash
          chmod +x test/test.bash
          bash -xv test/test.bash
